# Generated by Django 2.0.3 on 2018-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_vote', '0002_auto_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
